version: '3.8'

services:
  server:
    build: ./transcription-server
    ports:
      - "5000:5000"
    env_file:
      - ./transcription-server/.env
    volumes:
      - ./transcription-server/storage:/app/storage
    restart: unless-stopped

  client:
    build: ./transcription-client
    ports:
      - "5173:5173"
    environment:
      - VITE_SERVER_URL=http://localhost:5000
    restart: unless-stopped
